### PR TITLE
feat: add middleware for marblejs

### PR DESCRIPTION
**Pull request by aizerin**
#### Summary

I've added middleware for marblejs

https://marblejs.com/

### CODE REVIEW

**Comment by aizerin** [comment]
Yes, I just copied it from my running project.

**Comment by tdeekens** [comment]
> Yes, I just copied it from my running project.

You're aweomse. Let me publish it so you can remove the copy there. Thanks for contributing!

**Comment by tdeekens** [comment]
Voila. Give it a shot and let me know if it works as expected for you: https://www.npmjs.com/package/@promster/marblejs

**Comment by aizerin** [comment]
It works, thanks a lot :)

**Pull request merged**
